// Grounded Citation Validator (Flow B §17: Verify Evidence IDs [E1], [E2] and map verified sources)

import { Citation, EvidenceBlock } from './types';

export interface VerifiedCitationResult {
  answer: string;
  citedEvidences: Citation[];
  hasInvalidCitations: boolean;
  warnings: string[];
}

export class CitationValidator {
  /**
   * Parses Evidence IDs like [E1], [E2] from generated answer text,
   * verifies their existence against the retrieved evidence pool,
   * and returns programmatically verified citation metadata.
   */
  public static validateAndMapCitations(
    rawAnswer: string,
    evidencePool: EvidenceBlock[]
  ): VerifiedCitationResult {
    const warnings: string[] = [];
    const citedEvidences: Citation[] = [];

    // Regex to match [E1], [E2], [E10] etc.
    const citationRegex = /\[E(\d+)\]/g;
    const matches = Array.from(rawAnswer.matchAll(citationRegex));
    const citedIndices = new Set<number>();

    for (const match of matches) {
      const idx = parseInt(match[1], 10) - 1; // 1-indexed to 0-indexed
      if (idx >= 0 && idx < evidencePool.length) {
        citedIndices.add(idx);
      } else {
        warnings.push(`Phát hiện mã trích dẫn không hợp lệ: [E${idx + 1}] (Không nằm trong danh sách evidence).`);
      }
    }

    // Build verified citations list
    for (const idx of citedIndices) {
      citedEvidences.push(evidencePool[idx].citation);
    }

    // If no explicit [E#] citations were generated by LLM, fall back to all top retrieved evidence
    if (citedEvidences.length === 0 && evidencePool.length > 0) {
      evidencePool.slice(0, 3).forEach(e => citedEvidences.push(e.citation));
    }

    return {
      answer: rawAnswer,
      citedEvidences,
      hasInvalidCitations: warnings.length > 0,
      warnings
    };
  }
}
