import { Citation, EvidenceBlock } from './types';
import { SourceLocation } from '../document/types';

export interface FormattedSourceLocation {
  displayLabel: string;
  documentName: string;
  sourceType: string;
  sectionTitle?: string;
  pageStart?: number;
  pageEnd?: number;
  slideNumber?: number;
  sheetName?: string;
  cellRange?: string;
}

export interface VerifiedCitationResult {
  answer: string;
  citedEvidences: Citation[];
  formattedSources: FormattedSourceLocation[];
  hasInvalidCitations: boolean;
  warnings: string[];
}

export class CitationValidator {
  /**
   * Formats a generic SourceLocation into a clean, human-readable display label
   */
  public static formatSourceLocation(citation: Citation): FormattedSourceLocation {
    const docName = citation.documentName || 'document.pdf';
    const ext = docName.split('.').pop()?.toLowerCase() || 'pdf';
    const section = citation.sectionTitle || (citation.sectionPath && citation.sectionPath.length > 0 ? citation.sectionPath.join(' > ') : '');

    let displayLabel = `📄 ${docName}`;

    if (ext === 'pdf') {
      const pageStr = citation.pageStart ? `Trang ${citation.pageStart}` : '';
      displayLabel = [docName, pageStr, section].filter(Boolean).join(' · ');
    } else if (ext === 'docx') {
      displayLabel = `📝 ${docName}${section ? ' · ' + section : ''}`;
    } else if (ext === 'pptx') {
      const slide = citation.sourceLocation?.slideNumber || citation.pageStart || 1;
      displayLabel = `📊 ${docName} · Slide ${slide}${section ? ' · ' + section : ''}`;
    } else if (ext === 'xlsx') {
      const sheet = citation.sourceLocation?.sheetName || 'Sheet1';
      const cell = citation.sourceLocation?.cellRange ? ` (${citation.sourceLocation.cellRange})` : '';
      displayLabel = `📈 ${docName} · ${sheet}${cell}`;
    } else {
      displayLabel = [docName, section].filter(Boolean).join(' · ');
    }

    return {
      displayLabel,
      documentName: docName,
      sourceType: ext,
      sectionTitle: citation.sectionTitle,
      pageStart: citation.pageStart,
      pageEnd: citation.pageEnd,
      slideNumber: citation.sourceLocation?.slideNumber,
      sheetName: citation.sourceLocation?.sheetName,
      cellRange: citation.sourceLocation?.cellRange
    };
  }

  /**
   * Parses Evidence IDs like [E1], [E2] from generated answer text,
   * verifies their existence against the retrieved evidence pool,
   * and returns programmatically verified citation metadata.
   */
  public static validateAndMapCitations(
    rawAnswer: string,
    evidencePool: EvidenceBlock[]
  ): VerifiedCitationResult {
    const warnings: string[] = [];
    const citedEvidences: Citation[] = [];

    // Regex to match [E1], [E2], [E10] etc.
    const citationRegex = /\[E(\d+)\]/g;
    const matches = Array.from(rawAnswer.matchAll(citationRegex));
    const citedIndices = new Set<number>();

    for (const match of matches) {
      const idx = parseInt(match[1], 10) - 1; // 1-indexed to 0-indexed
      if (idx >= 0 && idx < evidencePool.length) {
        citedIndices.add(idx);
      } else {
        warnings.push(`Phát hiện mã trích dẫn không hợp lệ: [E${idx + 1}] (Không nằm trong danh sách evidence).`);
      }
    }

    // Build verified citations list
    for (const idx of citedIndices) {
      citedEvidences.push(evidencePool[idx].citation);
    }

    // If no explicit [E#] citations were generated by LLM, fall back to all top retrieved evidence
    if (citedEvidences.length === 0 && evidencePool.length > 0) {
      evidencePool.slice(0, 3).forEach(e => citedEvidences.push(e.citation));
    }

    const formattedSources = citedEvidences.map(c => CitationValidator.formatSourceLocation(c));

    return {
      answer: rawAnswer,
      citedEvidences,
      formattedSources,
      hasInvalidCitations: warnings.length > 0,
      warnings
    };
  }
}
